#!/usr/bin/env python

import httplib, sys

if len(sys.argv) < 2:
    print "usage: %s <markdown-file>" % sys.argv[0]
    sys.exit(-1)

with open(sys.argv[1], 'r') as f:
    markdown = f.read()

conn = httplib.HTTPSConnection('api.github.com')
headers = {'Content-Type': 'text/x-markdown', 'User-Agent': 'Python/httplib'}
conn.request('POST', '/markdown/raw', markdown, headers=headers)
response = conn.getresponse()

html = """
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
       """ + response.read() + """
    </div>
</body>
</html>
"""

conn.close()
sys.stdout.write(html)
